version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: rehearsal
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rehearsal
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data: {}